/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main.Teacher;



/**
 *
 * @author Asus
 */
public class TGurdianinfo extends javax.swing.JFrame {

    /**
     * Creates new form Gurdianinfo
     */
    public TGurdianinfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fname = new javax.swing.JLabel();
        fcon = new javax.swing.JLabel();
        foccu = new javax.swing.JLabel();
        fdes = new javax.swing.JLabel();
        fin = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        mname = new javax.swing.JLabel();
        mcon = new javax.swing.JLabel();
        moccu = new javax.swing.JLabel();
        mdes = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        close = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 944, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Gurdian Info");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 140, 20));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Father's Name");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Father's Contact No ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Father's Occupation");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Father's Designation");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Father's Annual Income");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 22));

        fname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        fname.setForeground(new java.awt.Color(0, 153, 153));
        fname.setText("jLabel8");
        jPanel2.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 200, 22));

        fcon.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        fcon.setForeground(new java.awt.Color(0, 153, 153));
        fcon.setText("jLabel9");
        jPanel2.add(fcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 200, 22));

        foccu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        foccu.setForeground(new java.awt.Color(0, 153, 153));
        foccu.setText("jLabel10");
        jPanel2.add(foccu, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 200, 22));

        fdes.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        fdes.setForeground(new java.awt.Color(0, 153, 153));
        fdes.setText("jLabel11");
        jPanel2.add(fdes, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 200, 22));

        fin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        fin.setForeground(new java.awt.Color(0, 153, 153));
        fin.setText("jLabel13");
        jPanel2.add(fin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 200, 22));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Mother's Name");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, -1, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("Mother's Contact No ");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("Mother's Occupation");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, -1, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setText("Mother's Designation");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, -1));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setText("Mother's Annual Income");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, -1, -1));

        mname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        mname.setForeground(new java.awt.Color(0, 153, 153));
        mname.setText("jLabel20");
        jPanel2.add(mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, 200, 22));

        mcon.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        mcon.setForeground(new java.awt.Color(0, 153, 153));
        mcon.setText("jLabel21");
        jPanel2.add(mcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, 200, 22));

        moccu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        moccu.setForeground(new java.awt.Color(0, 153, 153));
        moccu.setText("jLabel22");
        jPanel2.add(moccu, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, 200, 22));

        mdes.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        mdes.setForeground(new java.awt.Color(0, 153, 153));
        mdes.setText("jLabel23");
        jPanel2.add(mdes, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, 200, 22));

        min.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        min.setForeground(new java.awt.Color(0, 153, 153));
        min.setText("jLabel25");
        jPanel2.add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 220, 200, 22));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 33, 940, 285));

        close.setBackground(new java.awt.Color(232, 17, 35));
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Delete_30px.png"))); // NOI18N
        close.setBorderPainted(false);
        close.setContentAreaFilled(false);
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(912, 1, 30, 30));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Teacher Gurdian");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 8, -1, -1));

        jLabel43.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(204, 204, 255));
        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_School_30px.png"))); // NOI18N
        jLabel43.setText("Student Management System-");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 944, 320));

        setBounds(250, 200, 944, 320);
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        this.dispose();
       tpro.edt.setEnabled(true);
       tpro.loc.setEnabled(true);
       tpro.add.setEnabled(true);
       tpro.gur.setEnabled(true);
    }//GEN-LAST:event_closeActionPerformed

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        close.setOpaque(true);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        close.setOpaque(false);
    }//GEN-LAST:event_closeMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TGurdianinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TGurdianinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TGurdianinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TGurdianinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TGurdianinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    public static javax.swing.JLabel fcon;
    public static javax.swing.JLabel fdes;
    public static javax.swing.JLabel fin;
    public static javax.swing.JLabel fname;
    public static javax.swing.JLabel foccu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JLabel mcon;
    public static javax.swing.JLabel mdes;
    public static javax.swing.JLabel min;
    public static javax.swing.JLabel mname;
    public static javax.swing.JLabel moccu;
    // End of variables declaration//GEN-END:variables
}
